# Generated by Django 3.2.7 on 2021-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='operation',
            field=models.CharField(max_length=5),
        ),
    ]
