# Generated by Django 3.2.7 on 2021-09-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_alter_math_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='operation',
            field=models.CharField(choices=[('add', 'add'), ('sub', 'sub'), ('mul', 'mul'), ('div', 'div')], max_length=5),
        ),
    ]
