# Generated by Django 3.2.7 on 2021-09-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0005_alter_math_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maths.result'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('error__isnull', True), ('value__isnull', False)), models.Q(('error__isnull', False), ('value__isnull', True)), _connector='OR'), name='maths_result_value_error_together'),
        ),
    ]
